### ISSUE TITLE
java-lesson02: Inconsistent calls to startActive()

### ISSUE THREAD

**Issue by eest** [yurishkuro/opentracing-tutorial#16]
In the [lesson text](https://github.com/yurishkuro/opentracing-tutorial/tree/master/java/src/main/java/lesson02) only `sayHello()` uses `startActive(true)`, while  `formatString()` and `printHello()` calls `startActive()`. The solution file [HelloActive.java](https://github.com/yurishkuro/opentracing-tutorial/blob/master/java/src/main/java/lesson02/solution/HelloActive.java) calls `startActive(true)` in all functions. Which is the correct usage?

[](url)

**Comment by yurishkuro** [comment]
`startActive(true)` is correct, thanks for reporting it.
