### ISSUE TITLE
The program of [java lesson 3 solution] is defective.

### ISSUE THREAD

**Issue by KNishikura** [yurishkuro/opentracing-tutorial#37]
The source of the following "Formatter.java" is a problem.
If you look at the UI after execution, only three spans will be displayed.
It is necessary to display 5 spans.

Formatter.java 

>         try (JaegerTracer tracer = Tracing.init("formatter")) {
>             new Formatter(tracer).run(args);
>         }

By implementing it as described in the Readme, you can see five spans.

> Tracer tracer = Tracing.init("formatter");
> new Formatter(tracer).run(args);

The same applies to "Publisher.java".

Sincerely yours,
Kazuya Nishikura

**Comment by yurishkuro** [comment]
would you like to submit a merge request?

**Comment by KNishikura** [comment]
I do not know the essence of why this code is a problem.

**Comment by jpkrohling** [comment]
@KNishikura perhaps a good solution for now is to just change the `Formatter` class to be like the readme, so that it produces 5 spans?

**Comment by veterr** [comment]
I could do that pull request, but I get anauthorized message. Please authorise me (I am newbe to github, I input correct login and password to push to a new braunch "fixLesson03", but server rejects me)

**Comment by veterr** [comment]
Okey, did it

**Comment by yurishkuro** [comment]
do you mean PR #44?

**Comment by veterr** [comment]
Yes

**Comment by yurishkuro** [comment]
already addressed
