### ISSUE TITLE
Is it possible to make yaeger write results (spans) to db and pick them up on launch?

### ISSUE THREAD

**Issue by veterr** [yurishkuro/opentracing-tutorial#45]

**Comment by black-adder** [comment]
im not sure I follow what's being asked here. Also, the official jaeger repo https://github.com/jaegertracing/jaeger might be a better place for this question.

**Comment by justinclift** [comment]
Guessing here, but it sounds like @veterr is just starting out with Jaeger, so is probably using the default Jaeger (docker image?) which stores data to an in-memory database.  Each time that's restarted... it's all gone.

@veterr If that's the situation, you'll need to configure Jaeger to store the data in an external place.  According to the docs, Cassandra, ElasticSearch, and Kafka are supported, though other data store possibilities exist too:

* https://www.jaegertracing.io/docs/1.8/deployment/#storage-backends
* https://github.com/jaegertracing/jaeger/issues/638

Does that help? :smile:
