### ISSUE TITLE
Katacoda - Java - Lesson 1: JAVA_HOME is not defined correctly

### ISSUE THREAD

**Issue by maiermic** [yurishkuro/opentracing-tutorial#70]
I tried [OpenTracing Tutorial - Lesson 1](https://www.katacoda.com/opentracing/scenarios/opentracing-tutorial-lesson01) on Katacoda, but I get an error in step 1

```
$ ./run.sh lesson01.exercise.Hello Bryan
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-11-openjdk-amd64/bin/java
```

**Comment by yurishkuro** [comment]
I don't know where the origin of Katacoda tutorials is located (perhaps https://github.com/katacoda-scenarios/opentracing-scenarios), but it's not here, they are only "based" on these tutorials.

**Comment by maiermic** [comment]
Thank you for pointing me in the right direction :blush:
