### ISSUE TITLE
Tracing with message broker example in Go

### ISSUE THREAD

**Issue by xyluet** [yurishkuro/opentracing-tutorial#72]
Hi, I just started to implement my system with tracing, and since my system is heavily using message broker, is there any example or reference in Go for this?

**Comment by yurishkuro** [comment]
I recommend going through this tutorial to understand the basics, they are applicable in all situations. 

My book has an example of Kafka-based application: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/tree/master/Chapter05
